// This file was generated by WTL Dialog wizard 
// ParameterDialog.h : Declaration of the CParameterDialog

#pragma once

#include "resource.h"       // main symbols
#include <atlddx.h>

#include "FastDelegate.h"
#include "parameter.h"

class CParameterDialog : 
	public CDialogImpl<CParameterDialog>,
	public CWinDataExchange<CParameterDialog>	
{
public:
	CParameterDialog();
	~CParameterDialog();
	enum { IDD = IDD_DIALOG_PARAMETER };
	
	CUpDownCtrl m_wndSpinColor;
	CUpDownCtrl m_wndSpinSpeed;
	
    BEGIN_MSG_MAP(CParameterDialog)
		MESSAGE_HANDLER(WM_INITDIALOG, OnInitDialog)
        COMMAND_HANDLER(IDOK, BN_CLICKED, OnClickedOK)
        COMMAND_HANDLER(IDCANCEL, BN_CLICKED, OnClickedCancel)
		COMMAND_HANDLER(IDC_BUTTON_UPDATE, BN_CLICKED, OnBnClickedButtonUpdate)
	END_MSG_MAP()

	BEGIN_DDX_MAP(CParameterDialog)
		DDX_CONTROL_HANDLE(IDC_SPIN_COLOR, m_wndSpinColor)
		DDX_CONTROL_HANDLE(IDC_SPIN_SPEED, m_wndSpinSpeed)
	END_DDX_MAP()
    // Handler prototypes:
    //  LRESULT MessageHandler(UINT uMsg, WPARAM wParam, LPARAM lParam, BOOL& bHandled);
    //  LRESULT CommandHandler(WORD wNotifyCode, WORD wID, HWND hWndCtl, BOOL& bHandled);
    //  LRESULT NotifyHandler(int idCtrl, LPNMHDR pnmh, BOOL& bHandled);
	LRESULT OnInitDialog(UINT uMsg, WPARAM wParam, LPARAM lParam, BOOL& bHandled);
	LRESULT OnClickedOK(WORD wNotifyCode, WORD wID, HWND hWndCtl, BOOL& bHandled);
	LRESULT OnClickedCancel(WORD wNotifyCode, WORD wID, HWND hWndCtl, BOOL& bHandled);
	LRESULT OnBnClickedButtonUpdate(WORD /*wNotifyCode*/, WORD /*wID*/, HWND /*hWndCtl*/, BOOL& /*bHandled*/);

	void onChange();
	fastdelegate::FastDelegate1<Parameter> m_onParameterChangeDelegate;
	Parameter GetParameter();
};


